### ISSUE TITLE
JSON importer

### ISSUE THREAD

**Issue by thfield** [cycleready/cycleready-web#31]
we need a way to import json to the db.

lib/assets/routeSeedData.json in branch mapbox-play is an example of a seed file for Routes that I'd like to have as seed import file

**Comment by thfield** [comment]
lib/tasks/load_seed.rb is a modified version of this for CSV that I've used before.

**Comment by eternal44** [comment]
Thanks Tyler for putting up these issues!  Lets take a look at what we got tomorrow.

**Comment by eternal44** [comment]
@thfield as per our conversation I'll dump the json file into our db.

[https://github.com/cycleready/cycleready-web/blob/mapbox-play/lib/assets/routeSeedData.json](json file link)

**Comment by thfield** [comment]
done.  rake task: `rake data:load_data` will load data from json file lib/assets/routeSeedData.json

**Comment by thfield** [comment]
task has been renamed, use `rake data:init_hoods` and `rake data:init_routes`
